@gslApprenticeship
Feature: GSL Short Course Payments

As the Payments Service
I want to process earnings generated by the DAS Earnings Calculator for short course (apprenticeship unit) payments
So that the service can make the necessary payments to providers

Scenario: Short course training delivery that starts and completes in the same delivery period
	Given the payments service receives a CalculateGrowthAndSkillsPayments event for apprenticeship unit payments
	And the event contains the following earnings
		| Academic Year | Delivery Period | Earning Type | Amount |
		| 2526           | 11               | Milestone1    | 300    |
		| 2526           | 11               | Completion    | 700    |
	And the following collection periods are open
		| Collection Period | Academic Year |
		| R11                | 2526           |
	When the event is processed
	Then the following outgoing GSL Short Course Earnings Event is published
		| Collection Period | Academic Year | Delivery Period | Transaction Type | Amount |
		| R11                | 2526           | 11               | Milestone1        | 300    |
		| R11                | 2526           | 11               | Completion        | 700    |
	And all learner details, training details and payment details match the values on the incoming message
	And the incoming earnings have been saved in the Earnings Bridge cache tables
