<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>.net6.0;net8.0</TargetFrameworks>
	  <SelfContained>True</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ESFA.DC.ILR.2425.FundingService.FM36.FundingOutput.Model" Version="0.1.17" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="SFA.DAS.Payments.Messages.Common" Version="2.4.1-prerelease-62" />
		<PackageReference Include="SFA.DAS.Payments.Model.Core" Version="2.4.1-prerelease-62" />
	</ItemGroup>

</Project>
