<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetFramework>net8.0</TargetFramework>
    <IsServiceFabricServiceProject>True</IsServiceFabricServiceProject>
    <ServerGarbageCollection>True</ServerGarbageCollection>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <TargetLatestRuntimePatch>False</TargetLatestRuntimePatch>
    <UpdateServiceFabricManifestEnabled>True</UpdateServiceFabricManifestEnabled>
    <ServicePackagePath>PackageRoot</ServicePackagePath>
    <ServicePackagePrefix>$(MSBuildProjectName)</ServicePackagePrefix>
    <FabActUtilWorkingDir>$(BaseIntermediateOutputPath)\FabActUtilTemp</FabActUtilWorkingDir>
	<SelfContained>True</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="7.0.1" />
    <PackageReference Include="Autofac.ServiceFabric" Version="4.0.0" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.ServiceFabric" Version="10.0.1010" />
    <PackageReference Include="Microsoft.ServiceFabric.Actors" Version="7.0.1001" />
    <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" Version="7.0.1010" />
    <PackageReference Include="Microsoft.ServiceFabric.Data.Interfaces" Version="7.0.1010" />
    <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="7.0.1001" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="7.0.1001" />
    <PackageReference Include="SFA.DAS.Payments.Application" Version="2.4.1-prerelease-62" />
    <PackageReference Include="SFA.DAS.Payments.Core" Version="2.4.1-prerelease-62" />
    <PackageReference Include="SFA.DAS.Payments.Messages.Common" Version="2.4.1-prerelease-62" />
    <PackageReference Include="SFA.DAS.Payments.Model.Core" Version="2.4.1-prerelease-62" />
    <PackageReference Include="SFA.DAS.Payments.ServiceFabric.Core" Version="2.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.Payments.EarningEvents.Application\SFA.DAS.Payments.EarningEvents.Application.csproj" />
    <ProjectReference Include="..\SFA.DAS.Payments.EarningEvents.Domain\SFA.DAS.Payments.EarningEvents.Domain.csproj" />
    <ProjectReference Include="..\SFA.DAS.Payments.EarningEvents.ProcessLearnerService.Interfaces\SFA.DAS.Payments.EarningEvents.ProcessLearnerService.Interfaces.csproj" />      
  </ItemGroup>

</Project>
