<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetFramework>net8.0</TargetFramework>
    <IsServiceFabricServiceProject>True</IsServiceFabricServiceProject>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <TargetLatestRuntimePatch>False</TargetLatestRuntimePatch>
	<SelfContained>True</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Handlers\**" />
    <EmbeddedResource Remove="Handlers\**" />
    <None Remove="Handlers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="7.0.1" />
    <PackageReference Include="Autofac.ServiceFabric" Version="4.0.0" />
    <PackageReference Include="ESFA.DC.Logging" Version="0.1.4-beta0001" />
    <PackageReference Include="Microsoft.ServiceFabric" Version="10.0.1010" />
    <PackageReference Include="Microsoft.ServiceFabric.Actors" Version="7.0.1001" />
    <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="7.0.1001" />
    <PackageReference Include="Microsoft.ServiceFabric.Data.Interfaces" Version="7.0.1010" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="7.0.1001" />
    <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" Version="7.0.1010" />
    <PackageReference Include="SFA.DAS.Payments.Application" Version="2.4.1-prerelease-62" />
    <PackageReference Include="SFA.DAS.Payments.Core" Version="2.4.1-prerelease-62" />
    <PackageReference Include="SFA.DAS.Payments.Messages.Common" Version="2.4.1-prerelease-62" />
    <PackageReference Include="SFA.DAS.Payments.Model.Core" Version="2.4.1-prerelease-62" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
    <PackageReference Include="NServiceBus" Version="8.1.1" />
    <PackageReference Include="NServiceBus.Newtonsoft.Json" Version="3.0.0" />
    <PackageReference Include="NServiceBus.Transport.AzureServiceBus" Version="3.2.1" />
    <PackageReference Include="SFA.DAS.Payments.ServiceFabric.Core" Version="2.0.5" />
    <PackageReference Include="SFA.DAS.Payments.Monitoring.Jobs.Client" Version="0.5.8" />
    <PackageReference Include="SFA.DAS.Payments.Monitoring.Jobs.Messages" Version="0.5.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.Payments.EarningEvents.Application\SFA.DAS.Payments.EarningEvents.Application.csproj" />
    <ProjectReference Include="..\SFA.DAS.Payments.EarningEvents.Domain\SFA.DAS.Payments.EarningEvents.Domain.csproj" />
    <ProjectReference Include="..\SFA.DAS.Payments.EarningEvents.Messages.Internal\SFA.DAS.Payments.EarningEvents.Messages.Internal.csproj" />
    <ProjectReference Include="..\SFA.DAS.Payments.EarningEvents.Messages\SFA.DAS.Payments.EarningEvents.Messages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ESFA.DC.JobContextManager">
      <HintPath>C:\Users\dave_\.nuget\packages\esfa.dc.jobcontextmanager\0.2.1-beta0001\lib\netstandard2.0\ESFA.DC.JobContextManager.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
